apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - init-configmap.yaml
  - backup-pvc.yaml
  - backup-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: deep-quest
    includeSelectors: true
