from pydantic import Field

from common.schemas.project import (
    CareerExperience,
    Duration,
    ExperienceType,
    KeyAchievement,
    ProjectExperience,
    ProjectType,
)
from common.schemas.question import Question
from common.schemas.question_category import QuestionCategoryName
from common.state_model import BaseState, BaseStateConfig

# =============================================================================
# MOCK DATA FOR DEVELOPMENT/TESTING
# =============================================================================

MOCK_PROJECT_EXPERIENCE = ProjectExperience(
    project_name="주변시위 Now",
    project_description="서울시내 실시간 시위 정보 제공 및 참여 서비스",
    project_type=ProjectType.TEAM,
    team_composition="4명 (Backend 2, Frontend 2)",
    position=["Backend Developer", "Team Leader"],
    duration=Duration(
        start_date="2024-12",
        end_date="2025-04",
        is_current=False,
    ),
    tech_stack=[
        "Java 17",
        "Spring",
        "PostgreSQL",
        "Docker",
        "Jenkins",
        "Nginx",
        "RDS",
        "EC2",
        "Prometheus",
        "Grafana",
        "K6",
    ],
    architecture=None,
    key_achievements=[],
    links=[],
)

MOCK_KEY_ACHIEVEMENT = KeyAchievement(
    title="K6를 사용한 성능 테스트로 병목 식별 및 개선 (대규모 트래픽 간접 경험)",
    problems=[
        "실시간 시위 응원하기 기능에 대한 대규모 부하 예상에도 불구하고 성능 검증이 부족했습니다.",
    ],
    actions=[
        "Docker를 활용하여 t3.small 인스턴스와 유사한 환경 (2 Core, 2GB RAM)을 Mini PC에 구축하고, "
        "Spring, Prometheus, Grafana, K6를 활용해 성능 테스트 환경을 구성했습니다. "
        "10만 개의 데이터를 관련 테이블에 삽입하고, K6를 사용하여 600명의 가상 유저가 4분 동안 "
        "랜덤하게 시위를 응원하고 3초마다 응원 수를 조회하는 시나리오를 실행했습니다.",
    ],
    results=[
        "하드웨어 제약에 맞지 않는 HikariCP Connection Pool Size를 10개에서 4개로, "
        "Max Thread Pool Size를 10개에서 6개로 조절하여 평균 응답속도를 1.5s에서 1.12s로 25.3% 개선했습니다.",
        "불필요한 @Transactional을 제거하여 평균 응답속도를 1.12s에서 0.73s로 34.8% 개선했습니다.",
        "응원 데이터에 Redis Cache를 적용하여 DB 병목을 제거하고 평균 응답속도를 0.73s에서 0.07s로 "
        "90.4% 개선했습니다.",
    ],
    reflections=[],
)

# =============================================================================
# STATE MODELS
# =============================================================================


class Experience(BaseStateConfig):
    experience_type: ExperienceType = Field(
        description="The type of experience. 'CAREER' or 'PROJECT'",
        default=ExperienceType.PROJECT,
    )
    details: CareerExperience | ProjectExperience = Field(
        description="The experience details.",
        default=MOCK_PROJECT_EXPERIENCE,
    )


class InputState(BaseStateConfig):
    # applied_position
    applied_position: str = Field(
        default="Backend Developer",
        description="The applied position that is used to generate questions.",
    )
    # experience
    experience: Experience = Field(
        description="The experience that is used to generate questions.",
        default_factory=Experience,
    )
    # key_achievement
    key_achievement: KeyAchievement = Field(
        description="The key achievement that is used to generate questions.",
        default=MOCK_KEY_ACHIEVEMENT,
    )
    # question_categories
    question_categories: list[QuestionCategoryName] = Field(
        description="The question categories that user want to generate questions for.",
        default=[
            QuestionCategoryName.TECHNICAL_DECISION,
            QuestionCategoryName.TECHNICAL_DEPTH,
            QuestionCategoryName.PROBLEM_SOLVING,
            QuestionCategoryName.SCALABILITY,
        ],
    )
    # existing_questions
    existing_questions: list[Question] | None = Field(
        description="The existing questions should be considred while generating new questions.",
        default=None,
    )


class GraphState(InputState, BaseState):
    questions: list[Question] = Field(
        description="The questions generated by the model.",
        default_factory=list,
    )
